# Generated by Django 5.2.7 on 2025-12-18 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_gymuser_otp_remove_booking_email_remove_booking_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.gymuser'),
            preserve_default=False,
        ),
    ]
