# Generated by Django 5.2.7 on 2026-01-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='gymuser',
            name='name',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='preferred_time',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=10),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('medical_notes', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.gymuser')),
            ],
        ),
    ]
