# Generated by Django 5.2.7 on 2026-01-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_gymuser_is_verified_remove_gymuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_phone',
            field=models.CharField(max_length=20),
        ),
    ]
