# Generated by Django 5.2.7 on 2026-01-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_user_name_alter_booking_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
