# Generated by Django 5.2.7 on 2026-01-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_gymuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymuser',
            name='is_verified',
        ),
    ]
