# Generated by Django 5.2.7 on 2026-01-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_gymuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
